config/routes.rb
Rails.application.routes.draw do
  resources :prisons, only: [:show] do
    resources :criminals, only: [:new, :create]
  end
  resources :criminals, only: [:destroy] do
    resources :convictions, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/conviction.rb
class Conviction < ApplicationRecord
  belongs_to :crime
  belongs_to :criminal
  validates :crime, uniqueness: { scope: :criminal }
  # validates :criminal, uniqueness: { scope: :crime }
end

app/models/crime.rb
class Crime < ApplicationRecord
  has_many :convictions # crime.convictions
  has_many :criminals, through: :convictions
  validates :name, presence: true, uniqueness: true

  def to_label
    name.capitalize
  end
end

app/models/criminal.rb
class Criminal < ApplicationRecord
  belongs_to :prison # criminal.prison -> INSTANCE of a prison
  has_many :convictions, dependent: :destroy
  has_many :crimes, through: :convictions
  validates :name, presence: true
  has_one_attached :photo
  # validates :image_url, presence: true
end

app/models/prison.rb
class Prison < ApplicationRecord
  has_many :criminals # prison.criminals
  validates :name, presence: true
  validates :banner_url, presence: true
  # before_destroy :reassign_criminals

  # def reassign_criminals
  #   criminals.each do |criminal|
  #     prison = Prison.all.sample
  #     criminal.prison = prison
  #     criminal.save
  #   end
  # end
end

# prison.destroy
# error, you cant do this foreign_key restraint

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/convictions_controller.rb
class ConvictionsController < ApplicationController
  before_action :set_criminal, only: [:new, :create]
  def new
    @conviction = Conviction.new
    # @crimes = Crime.order(name: :asc)
    # @crimes = @criminal.crimes
    @crimes = Crime.where.not(id: @criminal.crimes).order(name: :asc)
  end

  def create
    @conviction = Conviction.new(conviction_params)
    @conviction.criminal = @criminal
    if @conviction.save
      redirect_to prison_path(@criminal.prison)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def conviction_params
    params.require(:conviction).permit(:crime_id)
  end

  def set_criminal
    @criminal = Criminal.find(params[:criminal_id])
  end

end

app/controllers/criminals_controller.rb
class CriminalsController < ApplicationController
  def new
    @prison = Prison.find(params[:prison_id])
    @criminal = Criminal.new # for the form
  end

  def create
    @prison = Prison.find(params[:prison_id])
    @criminal = Criminal.new(criminal_params)
    @criminal.prison = @prison
    if @criminal.save
      redirect_to prison_path(@prison)
    else
      # showing the new.html.erb form if it doesnt save
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @criminal = Criminal.find(params[:id])
    @criminal.destroy
    redirect_to prison_path(@criminal.prison), status: :see_other
  end

  private

  def criminal_params
    params.require(:criminal).permit(:name, :photo)
  end
end

app/controllers/prisons_controller.rb
class PrisonsController < ApplicationController
  def show
    @prison = Prison.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/convictions_helper.rb
module ConvictionsHelper
end

app/helpers/criminals_helper.rb
module CriminalsHelper
end

app/helpers/prisons_helper.rb
module PrisonsHelper
end

app/views/convictions/new.html.erb
<div class="container">
  <h1>Add Crime</h1>
  <%= simple_form_for [@criminal, @conviction] do |f| %>
    <%= f.association :crime, as: :radio_buttons, include_blank: false, collection: @crimes %>
    <%= f.submit 'Convict', class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/criminals/new.html.erb
<div class="container mt-3">
  <h1><%= @prison.name %></h1>
  <%= simple_form_for [@prison, @criminal] do |f| %>
    <%= f.input :name %>
    <%#= f.input :image_url %>
    <%= f.input :photo, as: :file %>
    <%= f.submit 'Incacerate', class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaximumSecurity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/prisons/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @prison.banner_url %>);">
  <div class="container">
    <h1>Welcome to <%= @prison.name %></h1>
    <p>Change your life commit a felony.</p>
    <%= link_to 'Incarcerate', new_prison_criminal_path(@prison), class: 'btn btn-danger' %>
  </div>
</div>
<div class="container mt-3">
  <div class="cards">
    <% @prison.criminals.each do |criminal| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= criminal.photo.attached? ? cl_image_path(criminal.photo.key)  : criminal.image_url %>)">
        <%= criminal.name %>
        <%= link_to criminal_path(criminal), data: { turbo_method: :delete, turbo_confirm: "Release #{criminal.name}?" }, class: 'card-remove-link' do %>
          <i class="fa-solid fa-person-through-window"></i>
        <% end %>
        <%= link_to new_criminal_conviction_path(criminal), class: 'card-convict-link' do %>
          <i class="fa-solid fa-gavel"></i>
        <% end %>
        <div class="card-tags">
          <% criminal.crimes.each do |crime| %>
            <span><%= crime.name %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>